language: java

install:
  - sh .travis-init.sh
  - ant build-gyro-lib
  - ant build-commons-lib
  - ant build-gson

script: ant compile

jdk: oraclejdk8

addons:
  apt:
    packages:
      - python3
